### ISSUE TITLE
general clean up

### ISSUE THREAD

**Issue by Remi-Gau** [boutiques/boutiques#670]
Given that nippopy will rely on boutiques and that I'd like to more systematically use boutiques to manage a whole bunch of bids apps (and the fact that the BIDS execution standard - now official is very boutiques inspired), I'd like to freshen up this repo.

My idea would be to:

- [x] move tests to github and start running them again (as far as I can tell travis does not run them anymore) (done in #674)
- [x] modernize packaging: move to pyproject.toml (done in #677)
- [x] simplify set up for testing so it can be run as easily locally as in CI (done in #674)
- [x] test on all maintained python version: so from 3.8 to 3.12 (done in #674)
- [x] adapt dependencies versions if necessary (done in #677)
- [x] add formating and linting tools (flake8, black, isort or ruff) and orchestrate their execution with pre-commit (done in #675)
- [x] the end goal would to be more compliant with the scientific python recommendations: https://learn.scientific-python.org/development/guides/repo-review/?repo=boutiques%2Fboutiques&branch=master

@glatard if that makes sense I may get started with this. I have @mathdugre near me physically so I may turn to him in person if I have questions.

**Comment by Remi-Gau** [comment]
The doc build could probably do with some simplification:
- only a single README (use myst if you want to stick to markdown)
- "sphinx-argparse" to help print the CLI in the doc

**Comment by Remi-Gau** [comment]
also automating the build of the website may be a good thing

**Comment by Remi-Gau** [comment]
closing this as this is mostly done
